<?php

namespace flowcode\roble\form;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-28 at 21:56:05.
 */
class BaseFormTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var BaseForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BaseForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers flowcode\roble\form\BaseForm::getField
     * @todo   Implement testGetField().
     */
    public function testGetField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\roble\form\BaseForm::getFieldError
     * @todo   Implement testGetFieldError().
     */
    public function testGetFieldError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\roble\form\BaseForm::addField
     * @todo   Implement testAddField().
     */
    public function testAddField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\roble\form\BaseForm::addValidator
     * @todo   Implement testAddValidator().
     */
    public function testAddValidator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\roble\form\BaseForm::removeValidator
     * @todo   Implement testRemoveValidator().
     */
    public function testRemoveValidator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\roble\form\BaseForm::isValid
     * @todo   Implement testIsValid().
     */
    public function testIsValid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\roble\form\BaseForm::bind
     * @todo   Implement testBind().
     */
    public function testBind() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
